export const carMakesString = `
      <option value="">Select Make</option>
      <option value="A13">ALFA ROMEO</option>
      <option value="A90">ALPINA</option>
      <option value="A15">ALPINE</option>
      <option value="A33">ASTON MARTIN</option>
      <option value="A38">AUDI</option>
      <option value="B16">B.M.W.</option>
      <option value="B07">BENTLEY</option>
      <option value="B80">BLUECAR</option>
      <option value="B74">BYD</option>
      <option value="C16">CHRYSLER</option>
      <option value="C19">CITROEN</option>
      <option value="D52">DFSK</option>
      <option value="F05">FERRARI</option>
      <option value="F06">FIAT</option>
      <option value="F15">FORD</option>
      <option value="F43">FOTON</option>
      <option value="G53">GAC</option>
      <option value="G52">GREAT WALL</option>
      <option value="H67">HIGER</option>
      <option value="H16">HONDA</option>
      <option value="H43">HYUNDAI</option>
      <option value="I30">INFINITI</option>
      <option value="I12">ISUZU</option>
      <option value="J01">JAGUAR</option>
      <option value="J05">JEEP</option>
      <option value="K20">KIA</option>
      <option value="K38">KOENIGSEGG</option>
      <option value="L02">LAMBORGHINI</option>
      <option value="L07">LAND ROVER</option>
      <option value="L20">LOTUS</option>
      <option value="M24">M.G.</option>
      <option value="M68">MAN</option>
      <option value="M12">MASERATI</option>
      <option value="MA1">MAXUS</option>
      <option value="M17">MAZDA</option>
      <option value="M97">MCLAREN</option>
      <option value="M20">MERCEDES BENZ</option>
      <option value="M84">MINI</option>
      <option value="M31">MITSUBISHI</option>
      <option value="M39">MORGAN</option>
      <option value="N06">NISSAN</option>
      <option value="O18">OHM</option>
      <option value="O05">OPEL</option>
      <option value="P57">PERODUA</option>
      <option value="P12">PEUGEOT</option>
      <option value="P64">POLESTAR</option>
      <option value="P20">PORSCHE</option>
      <option value="R08">RENAULT</option>
      <option value="R16">ROLLS ROYCE</option>
      <option value="S13">SEAT</option>
      <option value="SC9">SERES</option>
      <option value="SC6">SHINERAY</option>
      <option value="S26">SKODA</option>
      <option value="SC5">SOKON</option>
      <option value="SD2">SRM</option>
      <option value="S95">SSANGYONG</option>
      <option value="S42">SUBARU</option>
      <option value="S45">SUZUKI</option>
      <option value="T74">TESLA</option>
      <option value="T15">TOYOTA</option>
      <option value="V19">VOLKSWAGEN</option>
      <option value="V20">VOLVO</option>
`;
